name: Release

# 触发条件：创建tag时
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.3'
    
    - name: Install Dependencies
      run: go mod download
    
    # 构建多平台二进制文件
    - name: Build Binaries
      run: |
        # Linux amd64
        GOOS=linux GOARCH=amd64 go build -v -o kiro2api-linux-amd64 .
        
        # Linux arm64
        GOOS=linux GOARCH=arm64 go build -v -o kiro2api-linux-arm64 .
        
        # macOS amd64
        GOOS=darwin GOARCH=amd64 go build -v -o kiro2api-darwin-amd64 .
        
        # macOS arm64
        GOOS=darwin GOARCH=arm64 go build -v -o kiro2api-darwin-arm64 .
        
        # Windows amd64
        GOOS=windows GOARCH=amd64 go build -v -o kiro2api-windows-amd64.exe .
    
    # 创建Release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          kiro2api-linux-amd64
          kiro2api-linux-arm64
          kiro2api-darwin-amd64
          kiro2api-darwin-arm64
          kiro2api-windows-amd64.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
